/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile;

/**
 *
 * @author Dell
 */
public class home4 extends javax.swing.JFrame {

    /**
     * Creates new form home4
     */
    public home4() {
        initComponents();
        this.setBounds(160,100,1020,560);
        p3.setBounds(0,140,1020,390);
        p3.setVisible(false);
        p4.setBounds(0,0,1020,520);
        p4.setVisible(true);
        l1.setBounds(10,14,150,124);
        l4.setBounds(880,12,1029,122);
        cb1.setBounds(850,125,138,25);
        l1.setVisible(false);
         l4.setVisible(false);
          cb1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        p4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        p3.setBackground(new java.awt.Color(103, 0, 103));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile/Group (2).png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 40, 61, 90);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 0, 103), 2));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 30, 120, 110);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 0, 103));
        jLabel3.setText("MOBILE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 150, 70, 20);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile/Group (4).png"))); // NOI18N
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 40, 90, 90);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 0, 103), 2));
        jPanel4.add(jLabel5);
        jLabel5.setBounds(30, 30, 120, 110);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(103, 0, 103));
        jLabel7.setText("BILL");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(60, 150, 70, 20);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile/Group (5).png"))); // NOI18N
        jPanel5.add(jLabel8);
        jLabel8.setBounds(40, 40, 90, 90);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(103, 0, 103));
        jLabel10.setText("MOBILE REPAIR");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(20, 150, 130, 20);

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 0, 103), 2));
        jPanel5.add(jLabel9);
        jLabel9.setBounds(30, 30, 120, 110);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(103, 0, 103));
        jLabel11.setText("CUSTOMER");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(40, 150, 100, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile/Group (6).png"))); // NOI18N
        jPanel6.add(jLabel12);
        jLabel12.setBounds(40, 40, 90, 90);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 0, 103), 2));
        jPanel6.add(jLabel13);
        jLabel13.setBounds(30, 30, 120, 110);

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        jPanel1.add(p3);
        p3.setBounds(0, 150, 1040, 390);

        l4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\Group.png")); // NOI18N
        jPanel1.add(l4);
        l4.setBounds(910, 10, 90, 90);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile/maclogo4.png"))); // NOI18N
        jPanel1.add(l1);
        l1.setBounds(0, 0, 150, 150);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profile", "Change Password", "Add Profile", "Log Out" }));
        jPanel1.add(cb1);
        cb1.setBounds(890, 110, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 470, 120, 70);

        p4.setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\ezgif-5-8519e171c54e.gif")); // NOI18N
        p4.add(jLabel15);
        jLabel15.setBounds(10, 270, 600, 520);

        getContentPane().add(p4);
        p4.setBounds(420, 490, 740, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l4;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    // End of variables declaration//GEN-END:variables
}
