/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Dell
 */
class mymodel extends javax.swing.table.AbstractTableModel
{
    ResultSet rs1;
    ResultSetMetaData rsmd;
    mymodel(ResultSet rs)
    {
        try
        {
            rs1=rs;
            rsmd=rs1.getMetaData();
        }
        catch(Exception e)
    {
        System.out.print(e);
    }
    }
    
    
    @Override
    public int getRowCount() {
        try
        {
            rs1.last();
            return rs1.getRow();
        }
        catch(Exception e)
    {
        System.out.print(e);
        return -1;
    }
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getColumnCount() {
        try{
            return rsmd.getColumnCount();
        }
        catch(Exception e)
    {
        System.out.print(e);
        return -1;
    }
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
        try
        {
            rs1.absolute(rowIndex+1);
            return rs1.getObject(columnIndex+1);
        }
        catch(Exception e)
        {
            return null;
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public String getColumnName(int n)
    {
        try
        {
            return rsmd.getColumnName(n+1);
        }
        catch(Exception e)
        {
          System.out.print(e);
            return null;
        }
    }
}

public class home5 extends javax.swing.JFrame {

    /**
     * Creates new form home5
     */
    public home5() {
        initComponents();
         this.setBounds(200,100,920,560);
         //p5.setVisible(false);
        p1.setBounds(1,1,920,560);
        p1.setVisible(true);
         
      //p1.setVisible(true);
            try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","");
           Statement st=c.createStatement();
           ResultSet rs=st.executeQuery("select * from models");
//           if(rs.next())
//           {
//              mymodel m1=new mymodel(rs);
//              jt1.setModel(m1);
//              
//           }
               
            
       }
       catch(Exception e)
       {
           System.out.print(e);
       }
            
             try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","");
           Statement st=c.createStatement();
           ResultSet rs=st.executeQuery("select Brand from models");
           while(rs.next())
           {
              cb1.addItem(rs.getString(1));
              
           }
        
            
       }
       catch(Exception e)
       {
           System.out.print(e);
       }
           
             
               
             try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","");
           Statement st=c.createStatement();
           ResultSet rs=st.executeQuery("select Brand from models");
           while(rs.next())
           {
              cb4.addItem(rs.getString(1));
              
           }
        
            
       }
       catch(Exception e)
       {
           System.out.print(e);
       }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        cb4 = new javax.swing.JComboBox<>();
        cb5 = new javax.swing.JComboBox<>();
        cb6 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        cb3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1.setBackground(new java.awt.Color(103, 0, 103));
        p1.setLayout(null);

        cb4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BRAND" }));
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });
        p1.add(cb4);
        cb4.setBounds(30, 250, 190, 50);

        cb5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODEL" }));
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });
        p1.add(cb5);
        cb5.setBounds(30, 320, 190, 50);

        cb6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROM/ Storage" }));
        p1.add(cb6);
        cb6.setBounds(30, 390, 190, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile/Group (2).png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 40, 61, 90);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 0, 103), 2));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 30, 120, 110);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 0, 103));
        jLabel3.setText("NEW MOBILE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 150, 120, 20);

        p1.add(jPanel2);
        jPanel2.setBounds(30, 30, 190, 190);

        jButton2.setBackground(new java.awt.Color(153, 0, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD NEW PURCHASES");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p1.add(jButton2);
        jButton2.setBounds(690, 460, 190, 50);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dealer Name");
        p1.add(jLabel6);
        jLabel6.setBounds(350, 20, 180, 30);

        jTextField4.setBackground(new java.awt.Color(102, 0, 102));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField4.setSelectionColor(new java.awt.Color(255, 255, 255));
        p1.add(jTextField4);
        jTextField4.setBounds(350, 50, 310, 40);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dealer Moblie/Phone");
        p1.add(jLabel7);
        jLabel7.setBounds(350, 90, 180, 30);

        jTextField5.setBackground(new java.awt.Color(102, 0, 102));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField5.setSelectionColor(new java.awt.Color(255, 255, 255));
        p1.add(jTextField5);
        jTextField5.setBounds(350, 120, 310, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity");
        p1.add(jLabel8);
        jLabel8.setBounds(350, 160, 180, 30);

        jTextField6.setBackground(new java.awt.Color(102, 0, 102));
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField6.setSelectionColor(new java.awt.Color(255, 255, 255));
        p1.add(jTextField6);
        jTextField6.setBounds(350, 190, 310, 40);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Market Price");
        p1.add(jLabel9);
        jLabel9.setBounds(350, 230, 180, 30);

        jTextField7.setBackground(new java.awt.Color(102, 0, 102));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField7.setSelectionColor(new java.awt.Color(255, 255, 255));
        p1.add(jTextField7);
        jTextField7.setBounds(350, 260, 310, 40);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dealer Price");
        p1.add(jLabel10);
        jLabel10.setBounds(350, 300, 180, 30);

        jTextField8.setBackground(new java.awt.Color(102, 0, 102));
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField8.setSelectionColor(new java.awt.Color(255, 255, 255));
        p1.add(jTextField8);
        jTextField8.setBounds(350, 330, 310, 40);

        jTextField9.setBackground(new java.awt.Color(102, 0, 102));
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField9.setSelectionColor(new java.awt.Color(255, 255, 255));
        p1.add(jTextField9);
        jTextField9.setBounds(350, 400, 310, 40);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Purchasing Date");
        p1.add(jLabel11);
        jLabel11.setBounds(350, 370, 180, 30);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Addhar Number");
        p1.add(jLabel12);
        jLabel12.setBounds(350, 440, 180, 30);

        jTextField10.setBackground(new java.awt.Color(102, 0, 102));
        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField10.setSelectionColor(new java.awt.Color(255, 255, 255));
        p1.add(jTextField10);
        jTextField10.setBounds(350, 470, 310, 40);

        jButton3.setBackground(new java.awt.Color(153, 0, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add New Brand/Model/Ram");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        p1.add(jButton3);
        jButton3.setBounds(30, 460, 190, 50);

        p3.setBackground(new java.awt.Color(103, 0, 103));
        p3.setLayout(null);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BRAND" }));
        cb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb1MouseClicked(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        p3.add(cb1);
        cb1.setBounds(30, 250, 190, 50);

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODEL" }));
        cb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb2MouseClicked(evt);
            }
        });
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        p3.add(cb2);
        cb2.setBounds(30, 320, 190, 50);

        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROM/Storage" }));
        p3.add(cb3);
        cb3.setBounds(30, 390, 190, 50);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile/Group (2).png"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(60, 40, 61, 90);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 0, 103), 2));
        jPanel4.add(jLabel13);
        jLabel13.setBounds(30, 30, 120, 110);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(103, 0, 103));
        jLabel14.setText("OLD MOBILE");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(30, 150, 120, 20);

        p3.add(jPanel4);
        jPanel4.setBounds(30, 30, 190, 190);

        jButton4.setBackground(new java.awt.Color(153, 0, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ADD OLD PURCHASES");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        p3.add(jButton4);
        jButton4.setBounds(690, 460, 190, 50);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Customer Name");
        p3.add(jLabel15);
        jLabel15.setBounds(350, 20, 180, 30);

        jTextField11.setBackground(new java.awt.Color(102, 0, 102));
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField11.setSelectionColor(new java.awt.Color(255, 255, 255));
        p3.add(jTextField11);
        jTextField11.setBounds(350, 50, 310, 40);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Customer Moblie/Phone");
        p3.add(jLabel16);
        jLabel16.setBounds(350, 90, 180, 30);

        jTextField12.setBackground(new java.awt.Color(102, 0, 102));
        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField12.setSelectionColor(new java.awt.Color(255, 255, 255));
        p3.add(jTextField12);
        jTextField12.setBounds(350, 120, 310, 40);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Quantity");
        p3.add(jLabel17);
        jLabel17.setBounds(350, 160, 180, 30);

        jTextField13.setBackground(new java.awt.Color(102, 0, 102));
        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField13.setSelectionColor(new java.awt.Color(255, 255, 255));
        p3.add(jTextField13);
        jTextField13.setBounds(350, 190, 310, 40);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Market Price");
        p3.add(jLabel18);
        jLabel18.setBounds(350, 230, 180, 30);

        jTextField14.setBackground(new java.awt.Color(102, 0, 102));
        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField14.setSelectionColor(new java.awt.Color(255, 255, 255));
        p3.add(jTextField14);
        jTextField14.setBounds(350, 260, 310, 40);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Purchase Price");
        p3.add(jLabel19);
        jLabel19.setBounds(350, 300, 180, 30);

        jTextField15.setBackground(new java.awt.Color(102, 0, 102));
        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField15.setSelectionColor(new java.awt.Color(255, 255, 255));
        p3.add(jTextField15);
        jTextField15.setBounds(350, 330, 310, 40);

        jTextField16.setBackground(new java.awt.Color(102, 0, 102));
        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField16.setSelectionColor(new java.awt.Color(255, 255, 255));
        p3.add(jTextField16);
        jTextField16.setBounds(350, 400, 310, 40);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Purchasing Date");
        p3.add(jLabel20);
        jLabel20.setBounds(350, 370, 180, 30);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Addhar Number");
        p3.add(jLabel21);
        jLabel21.setBounds(350, 440, 180, 30);

        jTextField17.setBackground(new java.awt.Color(102, 0, 102));
        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTextField17.setSelectionColor(new java.awt.Color(255, 255, 255));
        p3.add(jTextField17);
        jTextField17.setBounds(350, 470, 310, 40);

        jButton5.setBackground(new java.awt.Color(153, 0, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add New Brand/Model/Ram");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        p3.add(jButton5);
        jButton5.setBounds(30, 460, 190, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        cb2.removeAll();
        String s1=(String) cb1.getSelectedItem();
                try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","");
           Statement st=c.createStatement();
           ResultSet rs=st.executeQuery("select Model from models where Brand='"+s1+"'");
           while(rs.next())
           {
              cb2.addItem(rs.getString(1));
              
           }
               
            
       }
       catch(Exception e)
       {
           System.out.print(e);
       }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb2MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cb2MouseClicked

    private void cb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb1MouseClicked

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        
          cb3.removeAll();
        String s1=(String) cb2.getSelectedItem();
                try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","");
           Statement st=c.createStatement();
           ResultSet rs=st.executeQuery("select ROM from models where Model='"+s1+"'");
           while(rs.next())
           {
              cb3.addItem(rs.getString(1));
              
           }
               
            
       }
       catch(Exception e)
       {
           System.out.print(e);
       }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        // TODO add your handling code here:
         String s1=(String) cb1.getSelectedItem();
                try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","");
           Statement st=c.createStatement();
           ResultSet rs=st.executeQuery("select Model from models where Brand='"+s1+"'");
           while(rs.next())
           {
              cb5.addItem(rs.getString(1));
              
           }
               
            
       }
       catch(Exception e)
       {
           System.out.print(e);
       }
    }//GEN-LAST:event_cb4ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        // TODO add your handling code here:
            String s1=(String) cb2.getSelectedItem();
                try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile","root","");
           Statement st=c.createStatement();
           ResultSet rs=st.executeQuery("select ROM from models where Model='"+s1+"'");
           while(rs.next())
           {
              cb6.addItem(rs.getString(1));
              
           }
               
            
       }
       catch(Exception e)
       {
           System.out.print(e);
       }
    }//GEN-LAST:event_cb5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JComboBox<String> cb4;
    private javax.swing.JComboBox<String> cb5;
    private javax.swing.JComboBox<String> cb6;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p3;
    // End of variables declaration//GEN-END:variables
}
